### ISSUE TITLE
[Bug]: no get_experiment_results

### ISSUE THREAD

**Issue by jkitchin** [CederGroupHub/alabos#84]
### Current behavior

At https://cedergrouphub.github.io/alabos/submit_experiments.html#get-the-results it suggests you get results with 

```
from alab_management import get_experiment_results

results = get_experiment_results(exp_id)
```

but this leads to 

```
File "/Users/jkitchin/Dropbox/emacs/projects/projects/claude/alabos/examples/claude-light/get_results.py", line 4, in <module>
    from alab_management import get_experiment_results
ImportError: cannot import name 'get_experiment_results' from 'alab_management' (/Users/jkitchin/Dropbox/emacs/projects/projects/claude/alabos/alab_management/__init__.py)
```

### Expected Behavior

Maybe it should be 

```
from alab_management.builders.experimentbuilder import get_experiment_result

results = get_experiment_result('67053622de1c825bbd241f2d')
print(results)
```

I think the issue is in https://github.com/CederGroupHub/alabos/blob/5b6f178dc1ca7a7b85f3c9fc23b578882db06902/alab_management/__init__.py#L6 and https://github.com/CederGroupHub/alabos/blob/5b6f178dc1ca7a7b85f3c9fc23b578882db06902/alab_management/builders/__init__.py#L6 where that function is not imported.

**Comment by idocx** [comment]
Thank you for testing and reporting the bug! I have created a fix to correctly import. I also updated the function name in the document from `get_experiment_results ` to `get_experiment_result` as it can only return one experiment result at a time.

That is, once the new update is merged, you should be able to use the following code (also updated in the document) to get the result. 
```
from alab_managementimport get_experiment_result

results = get_experiment_result('67053622de1c825bbd241f2d')
print(results)
```
